name: Deploy Vue Frontend to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          node-version: 20

      - name: Deploy to EC2
        env:
          EC2_USER: ubuntu
          EC2_HOST: 54.169.199.30
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
        run: |
          echo "$SSH_PRIVATE_KEY" | tr -d '\r' > private_key.pem
          chmod 600 private_key.pem
          ssh -o StrictHostKeyChecking=no -o ServerAliveInterval=30 -i private_key.pem $EC2_USER@$EC2_HOST << 'EOF'
            export CI=true
            sudo -u www-data -- sh -c '
              cd /var/www/money-manager-web-frontend &&
              git stash &&
              git pull origin main &&
              npm install --no-fund &&
              npm run build -- --logLevel error --no-progress > build.log 2>&1 || true
            '
            sudo systemctl restart nginx
          EOF
